/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GLOBAL = 6;
  /** RegularExpression Id. */
  int FUTURE = 7;
  /** RegularExpression Id. */
  int NEXT = 8;
  /** RegularExpression Id. */
  int UNTIL = 9;
  /** RegularExpression Id. */
  int ALL = 10;
  /** RegularExpression Id. */
  int EXIST = 11;
  /** RegularExpression Id. */
  int LIVE = 12;
  /** RegularExpression Id. */
  int DEADLOCK = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int PLACE = 17;
  /** RegularExpression Id. */
  int NAME = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<GLOBAL>",
    "<FUTURE>",
    "<NEXT>",
    "<UNTIL>",
    "<ALL>",
    "<EXIST>",
    "<LIVE>",
    "<DEADLOCK>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<PLACE>",
    "<NAME>",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
