/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package javacc;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTLSTATEMENT = 1;
  public int JJTDSTATEMENT = 2;
  public int JJTSTATEMENT = 3;
  public int JJTMULTISTATEMENT = 4;
  public int JJTALLSTATEMENT = 5;
  public int JJTESTATEMENT = 6;
  public int JJTAND = 7;
  public int JJTOR = 8;
  public int JJTNOT = 9;
  public int JJTVOID = 10;
  public int JJTNEXT = 11;
  public int JJTGLOBALLY = 12;
  public int JJTFINALY = 13;
  public int JJTUNTIL = 14;
  public int JJTPLACES = 15;
  public int JJTPLACENAME = 16;


  public String[] jjtNodeName = {
    "Start",
    "Lstatement",
    "Dstatement",
    "Statement",
    "MultiStatement",
    "AllStatement",
    "Estatement",
    "And",
    "Or",
    "Not",
    "void",
    "Next",
    "Globally",
    "Finaly",
    "Until",
    "Places",
    "placename",
  };
}
/* JavaCC - OriginalChecksum=a18132c66e1f158ee1e61cc08b3cfd50 (do not edit this line) */
