/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 6.0_1 */
package javacc;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultiStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAllStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNext node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGlobally node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFinaly node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUntil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPlaces node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTplacename node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=38ec10c9c1b19c3728a55b7382e3aa4b (do not edit this line) */
