/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 6.0_1 */
package javacc;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTLstatement node, Object data);
  public Object visit(ASTDstatement node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTMultiStatement node, Object data);
  public Object visit(ASTAllStatement node, Object data);
  public Object visit(ASTEstatement node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTNext node, Object data);
  public Object visit(ASTGlobally node, Object data);
  public Object visit(ASTFinaly node, Object data);
  public Object visit(ASTUntil node, Object data);
  public Object visit(ASTPlaces node, Object data);
  public Object visit(ASTplacename node, Object data);
}
/* JavaCC - OriginalChecksum=f16d74a0f385c7c1c450ea91aac024a4 (do not edit this line) */
